---
- name: Import Telegraf GPG signing key
  apt_key: url=https://repos.influxdata.com/influxdb.key state=present

- name: Add Telegraf repository
  apt_repository: repo='deb https://repos.influxdata.com/ubuntu trusty stable' state=present

- name: Install Telegraf packages
  apt: name=telegraf state=present

- name: Config Apache Telegraf
  template:
    src: telegraf.conf.j2
    dest: "{{ telegraf_conf_file_apache }}"

- name: Start the Telegraf service
  service: name=telegraf state=restarted