{
 "title": "Apache",
 "description": "Apache dashboard",
 "tags": [
  "influxdb",
  "telegraf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "Apache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$server",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "repeat": "server",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apache_Uptime",
     "query": "SELECT last(\"Uptime\") FROM \"apache\" WHERE $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apache_BusyWorkers",
     "query": "SELECT mean(\"BusyWorkers\") as \"busy\",mean(\"IdleWorkers\") as \"idle\"  FROM \"apache\" WHERE $timeFilter  AND host =~ /$server$/ GROUP BY time($interval),* fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apache_BusyWorkers",
     "query": "SELECT mean(\"CPULoad\") as \"cpu-load\" FROM \"apache\" WHERE $timeFilter  AND host =~ /$server$/ GROUP BY time($interval),* fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bytes per Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes per Req" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apache_BusyWorkers",
     "query": "SELECT mean(\"BytesPerReq\") as \"bytes-per-req\" FROM \"apache\" WHERE $timeFilter  AND host =~ /$server$/ GROUP BY time($interval),* fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bytes / Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apache_BusyWorkers",
     "query": "SELECT mean(\"BytesPerSec\") as \"bytes-per-sec\" FROM \"apache\" WHERE $timeFilter  AND host =~ /$server$/ GROUP BY time($interval),* fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests / Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apache_BusyWorkers",
     "query": "SELECT mean(\"ReqPerSec\") as \"req-per-sec\" FROM \"apache\"  WHERE $timeFilter  AND host =~ /$server$/ GROUP BY time($interval),* fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accesses / Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apache_BusyWorkers",
     "query": "SELECT non_negative_derivative(mean(\"TotalAccesses\"),1s) as \"total-accesses\" FROM \"apache\" WHERE $timeFilter  AND host =~ /$server$/ GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Score Board",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apache_BusyWorkers",
     "query": "SELECT mean(\"scboard_closing\") as \"closing\",mean(\"scboard_dnslookup\") as \"dnslookup\",mean(\"scboard_finishing\") as \"finishing\",mean(\"scboard_idle_cleanup\") as \"idle-cleanup\",mean(\"scboard_keepalive\") as \"keepalive\",mean(\"scboard_logging\") as \"logging\",mean(\"scboard_open\") as \"open\",mean(\"scboard_reading\") as \"reading\",mean(\"scboard_sending\") as \"sending\",mean(\"scboard_starting\") as \"starting\",mean(\"scboard_waiting\") as \"waiting\" FROM \"apache\" WHERE $timeFilter  AND host =~ /$server$/ GROUP BY time($interval),* fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}