---
- name: Import Grafana GPG signing key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana repository
  apt_repository: repo='deb https://packages.grafana.com/oss/deb stable main' state=present

- name: Install Grafana packages
  apt: name=grafana state=present

- name: Start the Grafana service
  service: name=grafana state=restarted